export const GRIEVANCE_STATUSES = {
  SUBMITTED: 'SUBMITTED',
  UNDER_REVIEW: 'UNDER_REVIEW',
  ASSIGNED: 'ASSIGNED',
  IN_PROGRESS: 'IN_PROGRESS',
  RESOLUTION_PROPOSED: 'RESOLUTION_PROPOSED',
  STUDENT_VERIFICATION: 'STUDENT_VERIFICATION',
  CLOSED: 'CLOSED',
  REOPENED: 'REOPENED',
  REJECTED: 'REJECTED',
  ESCALATED: 'ESCALATED',
} as const;

export type GrievanceStatus = (typeof GRIEVANCE_STATUSES)[keyof typeof GRIEVANCE_STATUSES];

/**
 * Valid state transitions mapping.
 * Each status maps to the array of permissible next statuses.
 */
export const ALLOWED_STATUS_TRANSITIONS: Record<GrievanceStatus, GrievanceStatus[]> = {
  SUBMITTED: [
    GRIEVANCE_STATUSES.UNDER_REVIEW,
    GRIEVANCE_STATUSES.ASSIGNED,
    GRIEVANCE_STATUSES.REJECTED,
    GRIEVANCE_STATUSES.ESCALATED,
  ],
  UNDER_REVIEW: [
    GRIEVANCE_STATUSES.ASSIGNED,
    GRIEVANCE_STATUSES.IN_PROGRESS,
    GRIEVANCE_STATUSES.REJECTED,
    GRIEVANCE_STATUSES.ESCALATED,
  ],
  ASSIGNED: [
    GRIEVANCE_STATUSES.IN_PROGRESS,
    GRIEVANCE_STATUSES.REJECTED,
    GRIEVANCE_STATUSES.ESCALATED,
    GRIEVANCE_STATUSES.UNDER_REVIEW,
  ],
  IN_PROGRESS: [
    GRIEVANCE_STATUSES.RESOLUTION_PROPOSED,
    GRIEVANCE_STATUSES.STUDENT_VERIFICATION,
    GRIEVANCE_STATUSES.ESCALATED,
    GRIEVANCE_STATUSES.UNDER_REVIEW,
  ],
  RESOLUTION_PROPOSED: [
    GRIEVANCE_STATUSES.STUDENT_VERIFICATION,
    GRIEVANCE_STATUSES.CLOSED,
    GRIEVANCE_STATUSES.REOPENED,
  ],
  STUDENT_VERIFICATION: [
    GRIEVANCE_STATUSES.CLOSED,
    GRIEVANCE_STATUSES.REOPENED,
  ],
  REOPENED: [
    GRIEVANCE_STATUSES.ASSIGNED,
    GRIEVANCE_STATUSES.IN_PROGRESS,
    GRIEVANCE_STATUSES.UNDER_REVIEW,
    GRIEVANCE_STATUSES.ESCALATED,
  ],
  ESCALATED: [
    GRIEVANCE_STATUSES.IN_PROGRESS,
    GRIEVANCE_STATUSES.ASSIGNED,
    GRIEVANCE_STATUSES.RESOLUTION_PROPOSED,
    GRIEVANCE_STATUSES.STUDENT_VERIFICATION,
  ],
  REJECTED: [
    GRIEVANCE_STATUSES.REOPENED, // Can be appealed or reopened by admin
  ],
  CLOSED: [
    GRIEVANCE_STATUSES.REOPENED, // Can be reopened if valid cause
  ],
};
